export const words = [
  // Animals
  'Alligator','Antelope','Badger','Barracuda','Beaver','Bison','Bobcat','Buffalo',
  'Buzzard','Camel','Caribou','Cheetah','Chipmunk','Cobra','Condor','Cougar',
  'Coyote','Crane','Cricket','Crocodile','Dingo','Dolphin','Donkey','Dragon',
  'Dragonfly','Eagle','Elephant','Falcon','Ferret','Flamingo','Gazelle','Gecko',
  'Gerbil','Gibbon','Giraffe','Gorilla','Grizzly','Hamster','Hedgehog','Hippo',
  'Hornet','Hummingbird','Hyena','Iguana','Jaguar','Jellyfish','Kangaroo','Koala',
  'Komodo','Lemur','Leopard','Lobster','Lynx','Macaw','Manatee','Mantis',
  'Marmot','Mongoose','Monitor','Moose','Muskrat','Narwhal','Ocelot','Octopus',
  'Ostrich','Otter','Panther','Parrot','Peacock','Pelican','Penguin','Pheasant',
  'Phoenix','Piranha','Platypus','Porcupine','Praying','Puffin','Python','Rabbit',
  'Raccoon','Rattler','Raven','Roadrunner','Rooster','Salamander','Salmon','Scorpion',
  'Seagull','Seahorse','Seabird','Shark','Skunk','Sloth','Sparrow','Squid',
  'Squirrel','Starfish','Stingray','Stoat','Stork','Swallow','Tapir','Tarantula',
  'Termite','Tiger','Toucan','Turkey','Turtle','Viper','Vulture','Walrus',
  'Warthog','Weasel','Wolverine','Wombat','Woodpecker','Yak','Zebra','Zebrafish',
  // Colors and shades
  'Amber','Amethyst','Apricot','Aqua','Auburn','Azure','Beige','Bronze',
  'Burgundy','Carmine','Cerulean','Chartreuse','Chestnut','Cobalt','Copper','Coral',
  'Crimson','Cyan','Ebony','Emerald','Fuchsia','Gold','Indigo','Ivory',
  'Jade','Khaki','Lavender','Lilac','Lime','Magenta','Mahogany','Maroon',
  'Midnight','Mocha','Mustard','Navy','Ochre','Olive','Onyx','Orange',
  'Orchid','Peach','Pearl','Periwinkle','Plum','Purple','Raspberry','Rose',
  'Ruby','Russet','Saffron','Sage','Salmon','Sapphire','Scarlet','Sienna',
  'Silver','Slate','Tan','Taupe','Teal','Topaz','Turquoise','Umber',
  'Vermillion','Violet','White','Cream','Blush','Dusty','Frosty','Misty',
  // Nature and landscapes
  'Avalanche','Bamboo','Bayou','Blizzard','Blossom','Boulder','Breeze','Brook',
  'Canyon','Cascade','Cedar','Cliff','Cloud','Comet','Coral','Crater',
  'Creek','Cyclone','Delta','Desert','Dew','Dune','Eclipse','Fjord',
  'Flower','Forest','Frost','Geyser','Glacier','Glen','Gust','Harbor',
  'Highland','Hurricane','Island','Jungle','Lagoon','Lava','Leaf','Lightning',
  'Lotus','Meadow','Meteor','Mirage','Monsoon','Moon','Mountain','Mud',
  'Nebula','Oasis','Petal','Pine','Planet','Prairie','Prism','Rain',
  'Rainbow','Rapid','Reef','Ridge','River','Rock','Shore','Sierra',
  'Spring','Star','Stone','Storm','Summit','Sunrise','Sunset','Surf',
  'Swamp','Thunder','Tide','Timber','Tornado','Tundra','Valley','Volcano',
  'Waterfall','Wave','Wildfire','Wind','Winter','Zephyr','Aurora','Boreal',
  // Food and drinks
  'Almond','Avocado','Biscuit','Blueberry','Brownie','Caramel','Cherry','Cinnamon',
  'Cobbler','Coconut','Cookie','Cupcake','Custard','Eclair','Espresso','Fudge',
  'Ginger','Hazelnut','Honey','Lemon','Licorice','Macaron','Mango','Maple',
  'Marshmallow','Melon','Mint','Mochi','Mousse','Muffin','Nougat','Peach',
  'Pecan','Peppermint','Pistachio','Pretzel','Pudding','Pumpkin','Raisin','Sesame',
  'Sherbet','Sorbet','Spearmint','Strawberry','Toffee','Truffle','Vanilla','Walnut',
  'Waffles','Caramelized','Butterscotch','Cheddar','Cider','Clementine','Cobbler','Dragonfruit',
  // Objects and things
  'Anchor','Anvil','Arrow','Beacon','Bell','Blade','Bolt','Bow',
  'Candle','Castle','Chain','Charm','Clock','Compass','Crown','Crystal',
  'Dagger','Diamond','Dice','Door','Drum','Feather','Flag','Flute',
  'Fortress','Gem','Globe','Hammer','Helmet','Horn','Hourglass','Key',
  'Lantern','Locket','Map','Mask','Mirror','Needle','Orb','Pendant',
  'Pillar','Prism','Puzzle','Quill','Ring','Rod','Rune','Scroll',
  'Shield','Sphere','Spire','Staff','Stone','Sword','Tome','Torch',
  'Tower','Trumpet','Vase','Vault','Wand','Watch','Wheel','Whistle',
  // Adjectives
  'Ancient','Bold','Brave','Bright','Calm','Clever','Cosmic','Daring',
  'Dark','Distant','Divine','Dreamy','Dynamic','Epic','Eternal','Fearless',
  'Fierce','Frozen','Giant','Glowing','Golden','Grand','Heroic','Hidden',
  'Hollow','Icy','Infinite','Iron','Jade','Keen','Legendary','Limitless',
  'Lone','Loyal','Lucid','Luminous','Majestic','Mighty','Mystic','Neon',
  'Noble','Obscure','Peaceful','Phantom','Primal','Prime','Radiant','Rapid',
  'Royal','Sacred','Shadow','Shining','Silent','Silver','Sleek','Soaring',
  'Solar','Steadfast','Steel','Stellar','Stormy','Strange','Supreme','Swift',
  'Timeless','Titan','True','Twilight','Ultimate','Undying','Vast','Vibrant',
  'Victorious','Wild','Wise','Wondrous','Zealous','Agile','Arctic','Astral',
  // Places and locations
  'Academy','Abyss','Aerie','Arena','Archive','Bastion','Bazaar','Cavern',
  'Chapel','Citadel','Cloister','Colony','Cove','Domain','Dungeon','Enclave',
  'Expanse','Frontier','Gallery','Gateway','Grove','Haven','Hollow','Hub',
  'Kingdom','Labyrinth','Lair','Library','Lighthouse','Loft','Manor','Market',
  'Monastery','Monument','Nexus','Outpost','Palace','Passage','Peak','Portal',
  'Realm','Refuge','Ruin','Sanctum','Sanctuary','Shrine','Spire','Stronghold',
  'Temple','Terrain','Territory','Threshold','Vault','Village','Vista','Wasteland',
  // Abstract concepts
  'Balance','Bliss','Chaos','Clarity','Cosmos','Courage','Dawn','Destiny',
  'Echo','Ember','Enigma','Essence','Eternity','Fable','Fantasy','Fate',
  'Freedom','Glory','Grace','Harmony','Hope','Honor','Illusion','Infinity',
  'Justice','Legend','Liberty','Lore','Luck','Luminary','Memory','Miracle',
  'Mystery','Myth','Oracle','Paradox','Passion','Phantom','Power','Pride',
  'Promise','Quest','Riddle','Saga','Serenity','Signal','Silence','Solace',
  'Soul','Spirit','Strength','Symbol','Tale','Tranquil','Truth','Unity',
  'Valor','Victory','Vision','Virtue','Wisdom','Wonder','Zeal','Radiance',
  // Action words used as nouns
  'Ascent','Blaze','Burst','Chase','Clash','Dash','Drive','Drift',
  'Flight','Flicker','Forge','Gaze','Glide','Gleam','Grind','Guard',
  'Haunt','Hunt','Ignite','Impact','Inspire','Jump','Launch','Leap',
  'March','Pierce','Plunge','Pulse','Reach','Rise','Rush','Scout',
  'Search','Seek','Shine','Spark','Sprint','Surge','Sweep','Swing',
  'Track','Trek','Thrust','Venture','Wander','Watch','Whirl','Yield',
  // Mythological / Fantasy
  'Aegis','Aether','Ambrosia','Arcane','Archon','Ardent','Atlas','Basilisk',
  'Centaur','Chimera','Cyclops','Daemon','Djinn','Drake','Druid','Dryad',
  'Eldritch','Elf','Elven','Empyrean','Enchant','Eon','Faerie','Fenrir',
  'Golem','Griffin','Hydra','Kraken','Lich','Mage','Merlin','Minotaur',
  'Nymph','Ogre','Olympus','Oracle','Paladin','Pegasus','Phoenix','Roc',
  'Satyr','Siren','Specter','Sphinx','Sylph','Templar','Titan','Troll',
  'Unicorn','Valkyrie','Vampire','Warlock','Witch','Wizard','Wraith','Wyrm',
  // More nature
  'Acacia','Arroyo','Aspen','Bayberry','Birch','Briar','Canopy','Cattail',
  'Cavern','Clover','Cobblestone','Copse','Crevice','Crocus','Cypress','Dahlia',
  'Dandelion','Dapple','Ebbtide','Edgewater','Estuary','Fallow','Fennel','Fern',
  'Foxglove','Frond','Furrow','Gale','Garnet','Goldenrod','Granite','Gravel',
  'Grotto','Hawthorn','Heather','Hemlock','Holly','Hollow','Icicle','Jasmine',
  'Juniper','Kelp','Larkspur','Lichen','Lilac','Limestone','Linden','Magnolia',
  'Mangrove','Marigold','Marsh','Milkweed','Mistletoe','Moss','Mulberry','Nightshade',
  'Oak','Obsidian','Peony','Pebble','Quartz','Reed','Rosewood','Sassafras',
  'Sedge','Sequoia','Shale','Snowdrop','Sorrel','Sundew','Tamarack','Thicket',
  'Thistle','Thornwood','Tidepool','Topsoil','Treeline','Tundra','Undergrowth','Verdant',
  'Vervain','Vetch','Wheatgrass','Willow','Yarrow','Yew','Zinnia','Cliffside',
  // Tech and space
  'Algorithm','Antenna','Aperture','Arc','Array','Atom','Beacon','Bit',
  'Byte','Cache','Circuit','Code','Core','Cursor','Data','Debug',
  'Dimension','Domain','Drive','Echo','Electron','Engine','Epoch','Field',
  'Firmware','Flash','Flux','Frequency','Fusion','Galaxy','Grid','Hardware',
  'Horizon','Hub','Impulse','Index','Input','Ion','Kernel','Laser',
  'Layer','Link','Logic','Loop','Matrix','Module','Network','Node',
  'Optic','Orbit','Output','Packet','Parse','Patch','Pixel','Platform',
  'Probe','Protocol','Pulse','Query','Queue','Radar','Relay','Remote',
  'Render','Script','Sector','Sequence','Signal','Socket','Source','Stack',
  'Static','Stream','Switch','Sync','System','Terminal','Token','Upload',
  'Vector','Vertex','Virtual','Voltage','Vortex','Wire','Zero','Cipher',
  // Gemstones and minerals
  'Agate','Alabaster','Alexandrite','Andalusite','Aquamarine','Aragonite','Beryl','Calcite',
  'Carnelian','Chalcedony','Chrysolite','Citrine','Corundum','Diamond','Dolomite','Feldspar',
  'Flint','Fluorite','Garnet','Gypsum','Halite','Hematite','Jasper','Labradorite',
  'Lapis','Malachite','Mica','Moonstone','Obsidian','Olivine','Onyx','Opal',
  'Peridot','Pyrite','Quartz','Rhodonite','Rutile','Selenite','Serpentine','Spessartite',
  'Spinel','Sunstone','Tanzanite','Tourmaline','Turquoise','Variscite','Vesuvianite','Zircon',
  // Weather and atmosphere
  'Bluster','Cirrus','Cumulus','Cyclone','Downdraft','Downpour','Drizzle','Dusk',
  'Flurry','Fog','Forecast','Gust','Hailstone','Haze','Heatwave','Hoarfrost',
  'Humidity','Nimbus','Overcast','Permafrost','Precipitation','Sleet','Smog','Snowfall',
  'Squall','Stratus','Sunburst','Tempest','Thundercloud','Twilight','Updraft','Vortex',
  'Waterspout','Whirlwind','Windshear','Zenith','Zonal','Derecho','Inversion','Lenticular',
  // Emotions and virtues
  'Awe','Benevolence','Compassion','Conviction','Curiosity','Dedication','Devotion','Dignity',
  'Discipline','Empathy','Endurance','Enthusiasm','Equity','Excellence','Fairness','Faith',
  'Fortitude','Fulfillment','Generosity','Gratitude','Humility','Ingenuity','Integrity','Intuition',
  'Kindness','Mastery','Mindfulness','Patience','Perseverance','Poise','Purpose','Resilience',
  'Reverence','Sincerity','Tenacity','Thankfulness','Thoughtfulness','Tolerance','Transcendence',
];

export function generateGameName() {
  const pick = () => words[Math.floor(Math.random() * words.length)];
  return `${pick()} ${pick()} ${pick()}`;
}
